spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            username: root
            password: 123456
            url: jdbc:mysql://localhost:3306/es_db?useSSL=false&useUnicode=true&characterEncoding=utf-8
            driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none



augmented:
    # Api Keys
    SteamApiKey: ""
    OpenCriticKey: ""
    IsThereAnyDealKey: ""
    TwitchApiKey: ""

    # Server endpoints
    WSGFEndpoint: ""
    KeyLOLEndpoint: ""
    SteamSpyEndpoint: ""
    SteamToolsApiEndpoint: ""
    OpenCriticEndpoint: ""
    SteamRepEndpoint: ""
    PCGWEndpoint: ""

